sudo: false
language: node_js
node_js:
  - "8.1.0"
before_install: 
  - npm install
cache:
  directories:
    - node_modules
script: 
  - npm run gulp
  - npm run gulpmin
  - npm run webpack
  - npm run rollup
  - npm run rbabel
  - npm run karma
after_success:
  - bash <(curl -s https://codecov.io/bash)